frontend:
  replicas: 1
  image:
    repository: itsmedigio/app-of-apps-fe
    tag: latest
  config:
    default.conf: |
      server {
        listen       80;
        server_name  localhost;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        location / {
          try_files $uri $uri/ /index.html;
        }
      }
backend:
  replicas: 1
  image:
    repository: itsmedigio/app-of-apps-be
    tag: latest
database:
  replicas: 1
  image:
    repository: postgres
    tag: "13.1"
  credentials:
    username: postgres
    password: postgres
