image:
  repository: itsmedigio/app-of-apps-fe
  tag: latest
service:
  type: NodePort
  port: 80
  nodePort: 30080
ingress:
  enabled: false
config:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
